// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_ILALXNyBeXyAkiEg1Mx7dF8L9nCzCPk',
    appId: '1:20222035992:web:ecd353ba44cf7854a11b6d',
    messagingSenderId: '20222035992',
    projectId: 'flutter-auth-login-b0117',
    authDomain: 'flutter-auth-login-b0117.firebaseapp.com',
    storageBucket: 'flutter-auth-login-b0117.appspot.com',
    measurementId: 'G-9NV5HBKF5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7hwIhG82RtHwICy0OAbCZLBuEMVEM2gM',
    appId: '1:20222035992:android:7c4d32d7f87b98f6a11b6d',
    messagingSenderId: '20222035992',
    projectId: 'flutter-auth-login-b0117',
    storageBucket: 'flutter-auth-login-b0117.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCa-xjP2ahAFXzr1vlT5PSZljCgW0cAs8',
    appId: '1:20222035992:ios:bcfcafca6cdcf41fa11b6d',
    messagingSenderId: '20222035992',
    projectId: 'flutter-auth-login-b0117',
    storageBucket: 'flutter-auth-login-b0117.appspot.com',
    iosClientId: '20222035992-ovos92i35fn24mu1gleqiubua41c2l3n.apps.googleusercontent.com',
    iosBundleId: 'com.carlos.login.flutterLoginAuth',
  );
}
